services:
  ebrar-db:
    image: postgres:16-alpine
    container_name: ebrar-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EbrarKuruyemisDb
    ports:
      - "5433:5432"
    volumes:
      - ebrar_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ebrar-redis:
    image: redis:7-alpine
    container_name: ebrar-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ebrar_postgres_data:
